version: 0.2
phases: 
  install:
    runtime-versions:
      nodejs: 14

    commands:
      - echo begin build
      - cd client
      - npm install
  build:
    commands:
      - npm run build
      - echo build complete
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
      
